# Cooja supplies CONTIKI when rebuilding a configuration. For manual builds:
# gmake CONTIKI=/path/to/contiki-ng blackhole-router.cooja TARGET=cooja
CONTIKI ?= $(CONTIKI_NG)

MAKE_ROUTING = MAKE_ROUTING_RPL_LITE

include $(CONTIKI)/Makefile.include
